"""Add new models for tables, hall, usertype and updated halluser

Revision ID: 38ab1e8b5267
Revises: 7e2a435b5e24
Create Date: 2026-01-25 12:41:30.201836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38ab1e8b5267'
down_revision: Union[str, Sequence[str], None] = '7e2a435b5e24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('halls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_halls_id'), 'halls', ['id'], unique=False)
    op.create_index(op.f('ix_halls_name'), 'halls', ['name'], unique=True)
    op.create_table('user_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_types_id'), 'user_types', ['id'], unique=False)
    op.create_index(op.f('ix_user_types_type_name'), 'user_types', ['type_name'], unique=True)
    op.add_column('hall_users', sa.Column('hall_id', sa.Integer(), nullable=True))
    op.add_column('hall_users', sa.Column('user_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hall_users', 'halls', ['hall_id'], ['id'])
    op.create_foreign_key(None, 'hall_users', 'user_types', ['user_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hall_users', type_='foreignkey')
    op.drop_constraint(None, 'hall_users', type_='foreignkey')
    op.drop_column('hall_users', 'user_type_id')
    op.drop_column('hall_users', 'hall_id')
    op.drop_index(op.f('ix_user_types_type_name'), table_name='user_types')
    op.drop_index(op.f('ix_user_types_id'), table_name='user_types')
    op.drop_table('user_types')
    op.drop_index(op.f('ix_halls_name'), table_name='halls')
    op.drop_index(op.f('ix_halls_id'), table_name='halls')
    op.drop_table('halls')
    # ### end Alembic commands ###
