"""Initial migration

Revision ID: 7e2a435b5e24
Revises: 
Create Date: 2026-01-10 23:50:59.778484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e2a435b5e24'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hall_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hall_users_email'), 'hall_users', ['email'], unique=True)
    op.create_index(op.f('ix_hall_users_id'), 'hall_users', ['id'], unique=False)
    op.create_index(op.f('ix_hall_users_username'), 'hall_users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hall_users_username'), table_name='hall_users')
    op.drop_index(op.f('ix_hall_users_id'), table_name='hall_users')
    op.drop_index(op.f('ix_hall_users_email'), table_name='hall_users')
    op.drop_table('hall_users')
    # ### end Alembic commands ###
